/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.halun.tools.photo.location

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {

    @Test
	fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest)
    }
}
